### ISSUE TITLE
Test deploy to bluemix button.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/swift-enterprise-demo#67]

**Comment by rolivieri** [comment]
@christiancompton This can be tested now. Can you take this for a test drive?

**Comment by christiancompton** [comment]
Complete: 
![3f53909ae6c1c640](https://cloud.githubusercontent.com/assets/18534315/24102966/a5cff42c-0d4b-11e7-9525-b5f309b3a560.jpg)
