### ISSUE TITLE
Make app completely self-contained.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/swift-enterprise-demo#90]
- For demoing circuit breaker, let's just use an internal endpoint.

**Comment by TheSoundDefense** [comment]
The circuit breaker code has been removed from Kitura-Starter in a PR, and the Circuit Breaker endpoint has been moved into the SwiftEnterpriseDemo itself.

**Comment by rolivieri** [comment]
@TheSoundDefense  Great! Let's also update README file accordingly.
